# Generated by Django 2.1.1 on 2018-09-12 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dp_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ititle', models.CharField(max_length=20, verbose_name='标题')),
                ('iimg', models.ImageField(upload_to='dp_imgs', verbose_name='图片')),
                ('isDelete', models.BooleanField(default=False, verbose_name='删除')),
                ('iclick', models.IntegerField(verbose_name='点击量')),
                ('icontent', tinymce.models.HTMLField(verbose_name='简介')),
                ('itime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('ipraise', models.IntegerField(verbose_name='人气值')),
            ],
            options={
                'verbose_name': '图片详情',
                'verbose_name_plural': '图片详情',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20, verbose_name='标题')),
                ('isDelete', models.BooleanField(default=False, verbose_name='删除')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
            },
        ),
        migrations.AddField(
            model_name='imginfo',
            name='itype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp_show.TypeInfo', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='imginfo',
            name='iuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp_user.UserInfo', verbose_name='作者'),
        ),
    ]
