# Generated by Django 2.1.1 on 2018-09-13 14:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imginfo',
            name='iclick',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='imginfo',
            name='icontent',
            field=tinymce.models.HTMLField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='imginfo',
            name='ipraise',
            field=models.IntegerField(default=0, verbose_name='人气值'),
        ),
    ]
