# Generated by Django 2.1.1 on 2018-09-13 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dp_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='itime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='保存日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uintro',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uaddress',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uemail',
            field=models.CharField(max_length=30, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(max_length=20, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='unickname',
            field=models.CharField(default='', max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uphone',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='upwd',
            field=models.CharField(max_length=40, verbose_name='密码'),
        ),
    ]
