# Generated by Django 2.1.1 on 2018-09-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp_user', '0002_auto_20180913_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='itime',
            new_name='utime',
        ),
    ]
