# Generated by Django 2.1.1 on 2018-09-13 15:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_user', '0003_auto_20180913_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uintro',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=300, verbose_name='简介'),
        ),
    ]
